name: sobgog_currency_converter
description: Currency Converter App with support for dark and light mode. Created by Martin Gogolowicz ( Martin Gogołowicz ) | SobGOG.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  get: ^4.6.1
  sizer: ^2.0.15
  connectivity_plus: ^2.2.1
  unicons: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  
  assets:
  - assets/sobGOGlight.png
  - assets/sobGOGdark.png
